language: go

go:
    - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/golang/lint/golint
    - go get github.com/lestrrat/go-tcptest

install:
    - go get -d -v ./...
    - go vet ./...
    - test -z "$($HOME/gopath/bin/golint ./... | tee /dev/stderr)"
    - go build -v ./...

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci

